name: Protect Main Branch

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "$GITHUB_HEAD_REF" != release/* && "$GITHUB_HEAD_REF" != hotfix/* ]]; then
            echo "Pull requests to main must come from release/* or hotfix/* branches."
            exit 1
          fi
