name: Protect Develop Branch

on:
  pull_request:
    branches:
      - develop

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "$GITHUB_HEAD_REF" != release/* && "$GITHUB_HEAD_REF" != hotfix/* && "$GITHUB_HEAD_REF" != feature/* ]]; then
            echo "Pull requests to develop must come from release/* or hotfix/* or feature/* branches."
            exit 1
          fi
